# Generated by Django 2.0.5 on 2018-05-02 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='post published')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamerequest',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='gamerequest',
            name='likes',
        ),
        migrations.AddField(
            model_name='likes',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcoop_app.GameRequest'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
