# Generated by Django 2.0.5 on 2018-05-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0002_auto_20180503_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateField(blank=True, verbose_name='release date'),
        ),
    ]
