# Generated by Django 2.0.5 on 2018-05-03 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newcoop_app', '0003_auto_20180503_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=400)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='post published')),
                ('request',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcoop_app.GameRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='RequestLikes',
        ),
    ]
