# Generated by Django 2.0.5 on 2018-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0004_auto_20180503_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlikes',
            name='liked',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
