# Generated by Django 2.0.5 on 2018-05-05 23:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newcoop_app', '0005_requestlikes_liked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestlikes',
            unique_together={('request', 'user')},
        ),
    ]
