# Generated by Django 2.0.5 on 2018-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0006_auto_20180506_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
