# Generated by Django 2.0.5 on 2018-05-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0007_requestcomment_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcoop_app.Game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcoop_app.Platform')),
            ],
        ),
    ]
