# Generated by Django 2.0.5 on 2019-11-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0008_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(
                    choices=[(1, 'Co-op teammate'), (2, 'Squad member'), (3, 'Clan member'), (4, 'Competitor')],
                    max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['platform_name']},
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='newcoop_app.RequestType'),
        ),
    ]
