# Generated by Django 2.0.5 on 2019-11-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0009_auto_20191121_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school',
                 models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')],
                                  default='FR', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='gamerequest',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='newcoop_app.Student'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='request_type',
            field=models.IntegerField(
                choices=[(1, 'Co-op teammate'), (2, 'Squad member'), (3, 'Clan member'), (4, 'Competitor')]),
        ),
    ]
