# Generated by Django 2.0.5 on 2019-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0010_auto_20191121_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestType',
        ),
        migrations.AlterField(
            model_name='gamerequest',
            name='request_type',
            field=models.TextField(
                choices=[(1, 'Co-op teammate'), (2, 'Squad member'), (3, 'Clan member'), (4, 'Competitor')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
