# Generated by Django 2.0.5 on 2019-11-20 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0012_auto_20191121_0129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
