# Generated by Django 2.0.5 on 2019-11-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('newcoop_app', '0013_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequest',
            name='language',
            field=models.IntegerField(choices=[(1, 'Russian'), (2, 'English'), (3, 'Other')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamerequest',
            name='request_type',
            field=models.IntegerField(
                choices=[(1, 'Co-op teammate'), (2, 'Squad member'), (3, 'Clan member'), (4, 'Competitor')]),
        ),
    ]
